server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: asuka123
    sources:
      
      youtube: false 
      bandcamp: true
      
   
    plugins:
      - dependency: "dev.lavalink.youtube:youtube-plugin:1.15.0"
        snapshot: false
      - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
        repository: "https://maven.lavalink.dev/releases"
        snapshot: false

# //////////////////
# //////////////////
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    pot: "MnUyNDR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5YjR4ZGx5Yg=="
    visitorData: "Cgs1aTRrNWEwSDhfQSinwf7IBjIKCgJNWBIEGgAgLQ%3D%3D"
    oauth:
      enabled: true
      refreshToken: "TU_REFRESH_TOKEN_LARGO"
      skipInitialization: true

  lavasrc:
    providers: 
      - 'ytmsearch:"%ISRC%"'
      - 'ytmsearch:%QUERY%'
      - 'ytsearch:"%ISRC%"'
      - 'ytsearch:%QUERY%'
      - 'scsearch:%QUERY%'
    sources:
      spotify: true
      applemusic: false
      deezer: false
    spotify:
      clientId: "e5a80e386fce460bb3ff226e7eb32642"
      clientSecret: "3123ca9c43d945f781807a83bf07a5c3"
      countryCode: "MX"
      playlistLoadLimit: 200
      albumLoadLimit: 200


















