server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "asuka123"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.15.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

# ////////////////// CONFIGURACIÃ“N DE PLUGINS //////////////////
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    
    oauth:
      enabled: false
      skipInitialization: true

  lavasrc:
    providers: 
      - 'scsearch:"%ISRC%"'   
      - 'scsearch:%QUERY%'    
      - 'ytmsearch:"%ISRC%"'
      - 'ytmsearch:%QUERY%'
      - 'ytsearch:"%ISRC%"'
      - 'ytsearch:%QUERY%'

    sources:
      spotify: true
      applemusic: true
      deezer: false       
      yandexmusic: false
      flowerytts: false
      youtube: false

    spotify:
      clientId: "e5a80e386fce460bb3ff226e7eb32642"
      clientSecret: "3123ca9c43d945f781807a83bf07a5c3"
      countryCode: "MX"
      playlistLoadLimit: 200
      albumLoadLimit: 200





















